### ISSUE TITLE
PackageSupplier is missing from the SBOM

### ISSUE THREAD

**Issue by surendrapathak** [sethmlarson/cpython-sbom#6]
**Background**
cpython-sbom is building SPDX2.3 in Tag-Value format. [NTIA Minimum Element](https://www.ntia.doc.gov/files/ntia/publications/sbom_minimum_elements_report.pdf) has called out several fields as minimum requirements for making SBOM operational. Therefore every SBOM should try to include those fields.

**Actual Behavior**
The generated SBOM is missing PackageSupplier values.

**Expected Behavior**
PackageSupplier is a key field and as per recent [discussions](https://docs.google.com/document/d/13ZLHbFwR83JI6QDvyAyVtLo4hLgXdXGnyG4MT_fV16w/edit#heading=h.dzbvpnn6uwuh) in the CISA working group, it is possible to populate them with open-source project names or related contact detail

**Comment by sethmlarson** [comment]
Closed in https://github.com/sethmlarson/cpython-sbom/pull/4
