### ISSUE TITLE
SBOM is missing vulnerability lookup identifiers (CPE/PURL) for packages

### ISSUE THREAD

**Issue by surendrapathak** [sethmlarson/cpython-sbom#7]
**Background**
cpython-sbom is building SPDX2.3 in Tag-Value format. Vulnerability monitoring is considered a [key benefit of SBOM.](https://www.ntia.gov/files/ntia/publications/ntia_sbom_energy_jan2021overview_0.pdf) Therefore, the generated SBOM should attempt to populate vulnerability lookup keys as much as possible.

**Actual Behavior**
Generated SBOM is missing vulnerability lookup identifiers for multiple packages.

**Expected Behavior**
Missing vuln identifiers for tiny_sha3 and mpdecimal - there is no fixed answer to this but compared to the blank alternative, it is best to populate the identifier with _most likely values_ and make the vuln lookup probability greater than zero

**Comment by sethmlarson** [comment]
Closed in https://github.com/sethmlarson/cpython-sbom/pull/4
